### ISSUE TITLE
Support variables in default value of action inputs

### ISSUE THREAD

**Issue by RoopeshNair** [Azure/actions#2]
Support variables in default value of action inputs. 

For example, we could default the value of `creds` input to a variable `AZURE_CREDENTIALS` and the input can be optional in the workflow, if the variable is already defined in the repository. 

## Sample workflow file

```yaml
  # File: .github/workflows/workflow.yml
on: [push, pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:     
    - uses: azure/actions/login@master
```

## Azure login action metadata file

```yaml
# action.yml
# Login to Azure subscription
name: 'Login Azure'
description: 'Login Azure wraps the az login, allowing for Azure actions to log into Azure'
inputs: 
  creds: 
    description: `az ad sp create-for-rbac --name <> --scopes /subscriptions/<>/resourceGroups/<> --role contributor --sdk-auth` as value of secret variable: AZURE_CREDENTIALS'
    required: true
    default: '${{ secrets.AZURE_CREDENTIALS }}'
branding:
  icon: 'login.svg' # vector art to display in the GitHub Marketplace
  color: 'blue' # optional, decorates the entry in the GitHub Marketplace
runs:
  using: 'node'
  main: 'main.js'
```
