### ISSUE TITLE
CI/CD in Github Actions cannot find package.json on npm install

### ISSUE THREAD

**Issue by blfuentes** [Azure/actions#47]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: npm install  

## Environment
- Server - Azure Pipelines 
- Windows 'windows-latest'

## Issue Description

When trying to create a **yml** workflow for CI/CD Github Actions for an Angular WebApp the step with `npm install` fails because it cannot find the `package.json` file.

### Task 

```
name: Build and deploy Node.js app to Azure Web App - sleepdiary

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sleepdiary'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b2cd1103c29447b58c59b7122a70e852 }}
        package: .
```

### Error logs

> Run npm install
>   npm install
>   npm run build --if-present
>   npm run test --if-present
>   shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
> npm WARN saveError ENOENT: no such file or directory, open 'D:\a\SleepDiary\SleepDiary\package.json'
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN enoent ENOENT: no such file or directory, open 'D:\a\SleepDiary\SleepDiary\package.json'
> npm WARN SleepDiary No description
> npm WARN SleepDiary No repository field.
> npm WARN SleepDiary No README data
> npm WARN SleepDiary No license field.
> 
> up to date in 0.358s
> found 0 vulnerabilities
> 
> npm ERR! code ENOENT
> npm ERR! syscall open
> npm ERR! path D:\a\SleepDiary\SleepDiary\package.json
> npm ERR! errno -4058
> npm ERR! enoent ENOENT: no such file or directory, open 'D:\a\SleepDiary\SleepDiary\package.json'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\npm\cache\_logs\2020-09-28T07_29_03_363Z-debug.log
> npm ERR! code ENOENT
> npm ERR! syscall open
> npm ERR! path D:\a\SleepDiary\SleepDiary\package.json
> npm ERR! errno -4058
> npm ERR! enoent ENOENT: no such file or directory, open 'D:\a\SleepDiary\SleepDiary\package.json'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\npm\cache\_logs\2020-09-28T07_29_04_107Z-debug.log
> Error: Process completed with exit code 1.

**Comment by blfuentes** [comment]
The Repository needs to have the files on root folder.

**Comment by alisalim17** [comment]
Hi,

i have also same issue

https://github.com/alisalim17/airbnb-clone

**Comment by cireguisse** [comment]
Done in 0.04s.
yarn run v1.22.19
error Couldn't find a package.json file in "/home/runner/work/wedding-react/wedding-react"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

**Comment by Adophilus** [comment]
I noticed this error too. https://github.com/Adophilus/changenow-store/actions/runs/3255108218/jobs/5344079942#step:4:6

It seems like the folder somehow changes to <repo-name>/<repo-name> at (or before) npm install is run

**Comment by Adophilus** [comment]
The current solution I've found so far is here https://github.com/kuuumaaaa/blog-gatsby/issues/1

**Comment by imki123** [comment]
```
test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
```

`- uses: actions/checkout@v3` works for me.
