### ISSUE TITLE
Improving action code management

### ISSUE THREAD

**Issue by ajinkya599** [Azure/actions#86]
**<ins>PROBLEM STATEMENT</ins>**:
Here are some problems with how we manage code in our action repos:
- Committing <ins>build output</ins> - We commit the generated `js files` in code. It is not ideal to commit generated code manually.
- Committing <ins>node_modules</ins> - We commit `node_modules` changes in release branches. This makes PR review harder and can potentially lead to non-reviewed code getting checked-in to the repo as it is impossible to review the changes in `node_modules`.
- Making <ins>double commits</ins> - We manually `cherry-pick` changes from main to release branches.

**<ins>SOLUTION</ins>**:
Automate the committing of `js files` and `node_modules` and maintain versioning as recommended in the [release-process doc](https://github.com/Azure/actions/blob/main/docs/release-process.md).
- Keep active development in `main` branch.
- When the code is ready to be shipped, trigger the `Release workflow` with the new `releaseVersion`. This workflow will:
  - Checkout the _main_ branch, run the build, commit and push the generated files in a new branch '_releases/{releaseVersion}_'.
    <ins>Example</ins>: releaseVersion = `v2.0.1`, results in a new branch `releases/v2.0.1` forked from `master` and containing `js files` and `node_modules`.
  - Create a new tag '_releaseVersion_' pointing to the new '_releases/{releaseVersion}_' branch.
    <ins>Example</ins>: New tag `v2.0.1` gets created which points to `releases/v2.0.1` branch.
  - Find the '_majorVersion_' from '_releaseVersion_' and **force update** the tag 'majorVersion' to point to the new '_releases/{releaseVersion}_' branch.
    <ins>Example</ins>: Tag `v2` gets created/updated and points to `releases/v2.0.1` branch.

**<ins>POC</ins>**:
I forked `container-scan` action and created a POC that follows the above process:
[ajinkya599/container-scan](https://github.com/ajinkya599/container-scan/blob/master/.github/workflows/release-action.yml)
Here is the workflow:
```yaml
name: "Release action"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version. Example: v1.0.0'
        required: true
        default: 'v0.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      
      - name: Configure git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/ajinkya599/container-scan 
          git remote -v

      - name: Create local branch releases/${{ github.event.inputs.version}}
        run: |
          git checkout -b releases/${{ github.event.inputs.version}}

      - name: Build code
        run: |
          npm install
          npm run-script build
          npm prune --production

      - name: Detect major version
        run: |
          version=${{ github.event.inputs.version}}
          semver=(${version//./ })
          echo "MAJOR_VERSION=${semver[0]}" >> $GITHUB_ENV
          echo "Release major version is: ${semver[0]}"

      - name: Commit and push
        run: |
          # Commit generated files
          git add -f lib/
          git add -f node_modules/
          git commit -m "[Automation]: Adding generated files - js files and node_modules"

          # Push new release branch
          git push origin -u releases/${{ github.event.inputs.version}}

          # Create minor/patch release tag and push
          git tag -a ${{ github.event.inputs.version}} -m "Created ${{ github.event.inputs.version}} release"
          git push origin ${{ github.event.inputs.version}}

          # Create/update major release tag and force push
          git tag -fa ${{ env.MAJOR_VERSION }} -m "Add/update ${{ env.MAJOR_VERSION }} tag referencing -> ${{ github.event.inputs.version}}"
          git push origin ${{ env.MAJOR_VERSION }} --force

```

**<ins>LIMITATIONS</ins>**:
- A new release branch is created for all minor/patch versions.
- Force updating a given patch version is not automated in this approach (The principle here is that all the releases are immutable except for the major version).

**<ins>BONUS</ins>**:
- Today, for testing the changes, dev has to commit `js files` and `node_modules` in a branch. Can we facilitate manual testing for PRs, by creating a branch from the topic branch with all the generated code and share this in the PR?
